Repository servicemesher/trans, pull requests merged in 2018-10, with the labels that each got.

#135 Translation: Service Mesh and Middleware
  201810/does-the-service-mesh-spell-the-end-for-middleware.md
Labels: translation

#136 Translation: Raw TCP Traffic Shaping with Istio 1.1.0
  201810/raw-tcp-traffic-shaping-with-istio-1.1.0.md
Labels: translation

#139 practice for coohom using istio
  201810/practice-for-coohom-using-istio-in-production.md
Labels: original, tag/istio

#142 Translation: The Myth of Cloud-Native Portabilit
  201810/myth-cloud-native-portability.md
Labels: category/translation

#148 Translation: How to Map Cloud Native Workloads to Kubernetes Controllers
  201810/how-to-map-cloud-native-workloads-to-kubernetes-controllers.md
Labels: category/translation
